language: node_js
node_js:
  - '10.13.0'

dist: trusty
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "mariagoveas"
  skip_cleanup: true
  acl: public_read
  region: us-west-1